---
- name: Start Vector
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true
  listen: restart-vector
  when: ansible_virtualization_type not in ['docker', 'podman', 'container', 'containerd']
